### ISSUE TITLE
enigma2-plugin-extensions-alternativesoftcammanager.bb:do_compile) failed with exit code '1'

### ISSUE THREAD

**Issue by Ormiwhite** [Taapat/enigma2-plugin-alternativesoftcammanager#3]
hi ,
can u please help me to build this plugin with OE-A :

ERROR: enigma2-plugin-extensions-alternativesoftcammanager-1+gitAUTOINC+0464cc5928-r0 do_compile: 'python setup.py build ' execution failed.
ERROR: enigma2-plugin-extensions-alternativesoftcammanager-1+gitAUTOINC+0464cc5928-r0 do_compile: Function failed: do_compile (log file is located at /home/d-ina/OpenHDF/build-enviroment/builds/openspa/release/dm500hd/tmp/work/all-oe-linux/enigma2-plugin-extensions-alternativesoftcammanager/1+gitAUTOINC+0464cc5928-r0/temp/log.do_compile.28999)
ERROR: Logfile of failure stored in: /home/d-ina/OpenHDF/build-enviroment/builds/openspa/release/dm500hd/tmp/work/all-oe-linux/enigma2-plugin-extensions-alternativesoftcammanager/1+gitAUTOINC+0464cc5928-r0/temp/log.do_compile.28999
Log data follows:
| DEBUG: Executing shell function do_compile
| running build
| running build_py
| running build_trans
| sh: msgfmt: command not found
| ERROR: 'python setup.py build ' execution failed.
| Language compile po/ru.po -> build/lib/Extensions/AlternativeSoftCamManager/locale/ru/LC_MESSAGES/AlternativeSoftCamManager.mo
| Traceback (most recent call last):
|   File "setup.py", line 13, in <module>
|     cmdclass = setup_translate.cmdclass,
|   File "/home/d-ina/OpenHDF/build-enviroment/builds/openspa/release/dm500hd/tmp/work/all-oe-linux/enigma2-plugin-extensions-alternativesoftcammanager/1+gitAUTOINC+0464cc5928-r0/recipe-sysroot-native/usr/lib/python2.7/distutils/core.py", line 151, in setup
|     dist.run_commands()
|   File "/home/d-ina/OpenHDF/build-enviroment/builds/openspa/release/dm500hd/tmp/work/all-oe-linux/enigma2-plugin-extensions-alternativesoftcammanager/1+gitAUTOINC+0464cc5928-r0/recipe-sysroot-native/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
|     self.run_command(cmd)
|   File "/home/d-ina/OpenHDF/build-enviroment/builds/openspa/release/dm500hd/tmp/work/all-oe-linux/enigma2-plugin-extensions-alternativesoftcammanager/1+gitAUTOINC+0464cc5928-r0/recipe-sysroot-native/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
|     cmd_obj.run()
|   File "/home/d-ina/OpenHDF/build-enviroment/builds/openspa/release/dm500hd/tmp/work/all-oe-linux/enigma2-plugin-extensions-alternativesoftcammanager/1+gitAUTOINC+0464cc5928-r0/git/setup_translate.py", line 42, in run
|     _build.run(self)
|   File "/home/d-ina/OpenHDF/build-enviroment/builds/openspa/release/dm500hd/tmp/work/all-oe-linux/enigma2-plugin-extensions-alternativesoftcammanager/1+gitAUTOINC+0464cc5928-r0/recipe-sysroot-native/usr/lib/python2.7/distutils/command/build.py", line 127, in run
|     self.run_command(cmd_name)
|   File "/home/d-ina/OpenHDF/build-enviroment/builds/openspa/release/dm500hd/tmp/work/all-oe-linux/enigma2-plugin-extensions-alternativesoftcammanager/1+gitAUTOINC+0464cc5928-r0/recipe-sysroot-native/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
|     self.distribution.run_command(command)
|   File "/home/d-ina/OpenHDF/build-enviroment/builds/openspa/release/dm500hd/tmp/work/all-oe-linux/enigma2-plugin-extensions-alternativesoftcammanager/1+gitAUTOINC+0464cc5928-r0/recipe-sysroot-native/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
|     cmd_obj.run()
|   File "/home/d-ina/OpenHDF/build-enviroment/builds/openspa/release/dm500hd/tmp/work/all-oe-linux/enigma2-plugin-extensions-alternativesoftcammanager/1+gitAUTOINC+0464cc5928-r0/git/setup_translate.py", line 35, in run
|     raise Exception, "Failed to compile: " + src
| Exception: Failed to compile: po/ru.po
| WARNING: /home/d-ina/OpenHDF/build-enviroment/builds/openspa/release/dm500hd/tmp/work/all-oe-linux/enigma2-plugin-extensions-alternativesoftcammanager/1+gitAUTOINC+0464cc5928-r0/temp/run.do_compile.28999:1 exit 1 from 'exit 1'
| ERROR: Function failed: do_compile (log file is located at /home/d-ina/OpenHDF/build-enviroment/builds/openspa/release/dm500hd/tmp/work/all-oe-linux/enigma2-plugin-extensions-alternativesoftcammanager/1+gitAUTOINC+0464cc5928-r0/temp/log.do_compile.28999)
ERROR: Task (/home/d-ina/OpenHDF/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2-plugins/enigma2-plugin-extensions-alternativesoftcammanager.bb:do_compile) failed with exit code '1'

i use this config : https://github.com/Taapat/vuplus-fulan-openpli-oe-core/blob/master/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-alternativesoftcammanager.bb

but i think it's not compatible with OE-A
thankx

**Comment by Taapat** [comment]
Try in oe-alliance-core/meta-oe/classes/distutils-openplugins.bbclass: https://github.com/Taapat/vuplus-fulan-openpli-oe-core/commit/91eac2c1a5030c5ae049f3759ad111c5429c03cb

**Comment by Ormiwhite** [comment]
thanks dude , it's work .
