### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by Spaeleus** [Taapat/enigma2-plugin-alternativesoftcammanager#9]
Hi!

Here my italian translation.

Thanks a lot!

[AlternativeSoftCamManager-git40-2f55cbd-r0.0.zip](https://github.com/Taapat/enigma2-plugin-alternativesoftcammanager/files/13625088/AlternativeSoftCamManager-git40-2f55cbd-r0.0.zip)

**Comment by Taapat** [comment]
Thank you!
